- name: SET SOME STUFF
  hosts: all
  remote_user: root
  connection: local

  vars:
    - kev_message: This message starts in the playbook and is passed in a workflow

  tasks:
  - debug:
      msg: "STEP 1 kev_message is {{ kev_message }}"

  - set_stats:
      data:
        kev_message: "{{ kev_message }}"
        some_message: This is a message
        some_variable: 36

