---
- name: include some vars from a vault-encrypted file into our playbook
  hosts: all
  remote_user: root
  connection: local
  gather_facts: no

  vars:
  - vmware_datacenter: 'KEV Datacenter'
  - vmware_new_hostname: AnsiBuilt001
  - vmware_template_name: CentOS7-64-Tempalte
  - vmware_datastore: VMNFS
  - vmware_folder: '/'
  - vmware_disk_size: 20
  - vmware_ram_mb: 512
  - vm_cpu_count: 1
  - vm_core_per_cpu: 1
  - vmware_network: VLAN20


  tasks:
  - name: "Deploy new VM called {{ vmware_new_hostname }} with {{ vm_cpu_count }} CPUs, {{ vm_core_per_cpu }} cores, {{ vmware_disk_size }} HDD, {{ vmware_ram_mb }} RAM from {{ vmware_template_name }} template."
    vmware_guest:
      datacenter: "{{ vmware_datacenter }}"
      name: "{{ vmware_new_hostname }}"
      template: "{{ vmware_template_name }}"
      folder: "{{ vmware_folder }}"
      disk:
      - size_gb: "{{ vmware_disk_size }}"
        type: thin
        datastore: "{{ vmware_datastore }}"
      hardware:
        memory_mb: "{{ vmware_ram_mb }}"
        num_cpus: "{{ vm_cpu_count }}"
        num_cpu_cores_per_socket: "{{ vm_core_per_cpu }}"
    delegate_to: localhost

